version: "3"
services:
  nginx:
    build: .docker/nginx
    ports:
      - "80:80"
    depends_on:
      - php
      - mysql
    volumes:
      - .:/var/www/html
  php:
    build: .docker/php
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
  mysql:
    image: mysql:8.0
    volumes:
      - mysqldata:/var/lib/mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: transaction
      MYSQL_USER: transaction
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_NAME: mysql
volumes:
  mysqldata:
    driver: local